# Generated by Django 3.2.19 on 2023-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
