# Generated by Django 3.2.19 on 2023-06-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230630_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='publish',
        ),
    ]
