# Generated by Django 3.2.19 on 2023-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_recipe_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
